### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 1-eyx** [yusing/ComfyUI_TensorRT#6]
I don't even know how to use it, should I just put regular safetensores model in it or and engine model in it (the engine models does not even appear in the list)? when I tried the regular Realvis 4 this appeared.

![Screenshot (452)](https://github.com/yusing/ComfyUI_TensorRT/assets/133923407/e0668826-c37b-47ba-ae3c-b29094d94d7a)

**Comment by yusing** [comment]
Read the README. There is no need to build the engine separately. Old .engine file from other extensions cannot  be used. Just choose a safetensor.

From the error message,  model had been offloaded to CPU for some reason. Try restarting Comfy and try again.

**Comment by 1-eyx** [comment]
Of course I tried restarting and it didn't work.

**Comment by yusing** [comment]
> Of course I tried restarting and it didn't work.

What's the launch arguments you're using?

**Comment by yusing** [comment]
@jtabox @1-eyx fixed
